2025-05-16 20:23:56 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:23:56 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:23:56 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:07 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:07 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:07 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:07 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:07 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:07 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:07 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:07 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:07 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:08 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:08 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:08 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:12 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:12 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:12 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:12 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:13 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:13 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:13 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:13 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:13 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:13 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:13 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:13 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:13 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:13 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:13 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:13 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:13 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:13 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:14 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:14 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:15 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:15 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:17 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:17 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:17 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:17 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:18 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 20:24:20 - get_link - INFO - Капча решена успешно
2025-05-16 20:24:20 - get_link - INFO - Капча решена успешно
2025-05-16 20:24:20 - get_link - INFO - Капча решена успешно
2025-05-16 20:24:20 - get_link - INFO - Капча решена успешно
2025-05-16 20:24:20 - get_link - INFO - Капча решена успешно
2025-05-16 20:24:20 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:21 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:21 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:21 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:21 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:22 - get_link - INFO - Попытка решения капчи #2
2025-05-16 20:24:22 - get_link - INFO - Капча решена успешно
2025-05-16 20:24:23 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:23 - get_link - INFO - Капча решена успешно
2025-05-16 20:24:23 - get_link - INFO - Капча решена успешно
2025-05-16 20:24:23 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:23 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:23 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:23 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:23 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:24 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:24 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:24 - get_link - INFO - Капча решена успешно
2025-05-16 20:24:24 - get_link - INFO - Капча решена успешно
2025-05-16 20:24:24 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:24 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:24 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:24 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:24 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:24 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:25 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:25 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:25 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:26 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:27 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:27 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:27 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 20:24:28 - get_link - INFO - Капча решена успешно
2025-05-16 20:24:28 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:24:28 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:30 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 20:24:30 - get_link - INFO - Попытка решения капчи #3
2025-05-16 20:24:30 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:33 - get_link - INFO - Попытка решения капчи #2
2025-05-16 20:24:33 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:24:33 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[3]/div[1]/a
2025-05-16 20:24:33 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[3]/div[1]/a
2025-05-16 20:24:34 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[3]/div[1]/a
2025-05-16 20:24:34 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:34 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 20:24:34 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:35 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[3]/div[1]/a
2025-05-16 20:24:35 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:35 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:24:36 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:36 - get_link - INFO - Найдена ссылка по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:24:37 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 20:24:37 - get_link - ERROR - Ошибка при поиске (попытка 1): ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1395, in getresponse
    response.begin()
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 35, in get_first_yandex_link
    self._perform_search(query)
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 75, in _perform_search
    self.driver.get(f"https://yandex.ru/search/?text={encoded_query}&lr=213")
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 454, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1395, in getresponse
    response.begin()
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
2025-05-16 20:35:35 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:35:35 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:35:36 - get_link - ERROR - Ошибка при поиске (попытка 1): ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1395, in getresponse
    response.begin()
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 40, in get_yandex_links
    self._perform_search(query)
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 80, in _perform_search
    self.driver.get(f"https://yandex.ru/search/?text={encoded_query}&lr=213")
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 454, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1395, in getresponse
    response.begin()
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
2025-05-16 20:37:20 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:37:22 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:37:22 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:37:41 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:37:44 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:37:44 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:37:52 - get_link - ERROR - Ошибка при решении капчи с изображениями: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=136.0.7103.114)
Stacktrace:
	GetHandleVerifier [0x0039FC83+61635]
	GetHandleVerifier [0x0039FCC4+61700]
	(No symbol) [0x001C05D3]
	(No symbol) [0x001AFE20]
	(No symbol) [0x001CDD1F]
	(No symbol) [0x00233E8C]
	(No symbol) [0x0024DF19]
	(No symbol) [0x0022D096]
	(No symbol) [0x001FC840]
	(No symbol) [0x001FD6A4]
	GetHandleVerifier [0x006245A3+2701795]
	GetHandleVerifier [0x0061FD26+2683238]
	GetHandleVerifier [0x0063AA6E+2793134]
	GetHandleVerifier [0x003B6945+155013]
	GetHandleVerifier [0x003BD02D+181357]
	GetHandleVerifier [0x003A74D8+92440]
	GetHandleVerifier [0x003A7680+92864]
	GetHandleVerifier [0x00392070+5296]
	BaseThreadInitThunk [0x761F5D49+25]
	RtlInitializeExceptionChain [0x7726CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x7726CE31+561]
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 182, in _solve_image_captcha
    location = image_element.location
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 412, in location
    old_loc = self._execute(Command.GET_ELEMENT_RECT)["value"]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=136.0.7103.114)
Stacktrace:
	GetHandleVerifier [0x0039FC83+61635]
	GetHandleVerifier [0x0039FCC4+61700]
	(No symbol) [0x001C05D3]
	(No symbol) [0x001AFE20]
	(No symbol) [0x001CDD1F]
	(No symbol) [0x00233E8C]
	(No symbol) [0x0024DF19]
	(No symbol) [0x0022D096]
	(No symbol) [0x001FC840]
	(No symbol) [0x001FD6A4]
	GetHandleVerifier [0x006245A3+2701795]
	GetHandleVerifier [0x0061FD26+2683238]
	GetHandleVerifier [0x0063AA6E+2793134]
	GetHandleVerifier [0x003B6945+155013]
	GetHandleVerifier [0x003BD02D+181357]
	GetHandleVerifier [0x003A74D8+92440]
	GetHandleVerifier [0x003A7680+92864]
	GetHandleVerifier [0x00392070+5296]
	BaseThreadInitThunk [0x761F5D49+25]
	RtlInitializeExceptionChain [0x7726CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x7726CE31+561]

2025-05-16 20:37:52 - get_link - ERROR - Ошибка при проверке решения капчи: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0039FC83+61635]
	GetHandleVerifier [0x0039FCC4+61700]
	(No symbol) [0x001C044E]
	(No symbol) [0x001FBB08]
	(No symbol) [0x0022D156]
	(No symbol) [0x00228C22]
	(No symbol) [0x002281B6]
	(No symbol) [0x001936C5]
	(No symbol) [0x00193C1E]
	(No symbol) [0x001940AD]
	GetHandleVerifier [0x006245A3+2701795]
	GetHandleVerifier [0x0061FD26+2683238]
	GetHandleVerifier [0x0063AA6E+2793134]
	GetHandleVerifier [0x003B6945+155013]
	GetHandleVerifier [0x003BD02D+181357]
	(No symbol) [0x00193390]
	(No symbol) [0x00192B9D]
	GetHandleVerifier [0x007187FC+3701820]
	BaseThreadInitThunk [0x761F5D49+25]
	RtlInitializeExceptionChain [0x7726CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x7726CE31+561]
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 247, in _is_captcha_solved
    return bool(self.driver.find_elements(By.XPATH, '/html/body/div[1]/div[1]/header/form/div[1]'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 936, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0039FC83+61635]
	GetHandleVerifier [0x0039FCC4+61700]
	(No symbol) [0x001C044E]
	(No symbol) [0x001FBB08]
	(No symbol) [0x0022D156]
	(No symbol) [0x00228C22]
	(No symbol) [0x002281B6]
	(No symbol) [0x001936C5]
	(No symbol) [0x00193C1E]
	(No symbol) [0x001940AD]
	GetHandleVerifier [0x006245A3+2701795]
	GetHandleVerifier [0x0061FD26+2683238]
	GetHandleVerifier [0x0063AA6E+2793134]
	GetHandleVerifier [0x003B6945+155013]
	GetHandleVerifier [0x003BD02D+181357]
	(No symbol) [0x00193390]
	(No symbol) [0x00192B9D]
	GetHandleVerifier [0x007187FC+3701820]
	BaseThreadInitThunk [0x761F5D49+25]
	RtlInitializeExceptionChain [0x7726CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x7726CE31+561]

2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:09 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Попытка решения капчи #1
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:11 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 20:38:21 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:21 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:21 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:21 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:21 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:21 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:21 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:21 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:22 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:22 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:22 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:22 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:22 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:22 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:22 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:22 - get_link - INFO - Капча решена успешно
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:22 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:24 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:24 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:24 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:24 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:25 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:25 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 20:38:25 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 20:38:25 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:14:23 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:14:23 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:14:24 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:14:24 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:14:25 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:14:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:14:27 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:14:40 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:14:40 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:14:40 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:14:40 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:14:41 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:14:41 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:14:41 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:14:43 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:14:43 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:14:56 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:14:56 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:14:57 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:14:57 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:14:57 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:14:57 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:14:57 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:15:00 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:15:00 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:15:12 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:15:12 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:15:13 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:15:13 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:31:25 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:31:25 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:31:25 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:31:25 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:31:25 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:31:25 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:31:25 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:31:25 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:31:25 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:31:25 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:31:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:31:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:31:27 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:31:27 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:31:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:31:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:31:27 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:31:27 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:31:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:31:27 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:31:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:31:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:31:27 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:31:27 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:31:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:31:27 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:31:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:31:27 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:31:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:31:27 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:31:36 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 22:31:38 - get_link - INFO - Капча решена успешно
2025-05-16 22:31:38 - get_link - INFO - Капча решена успешно
2025-05-16 22:31:38 - get_link - INFO - Капча решена успешно
2025-05-16 22:31:38 - get_link - INFO - Капча решена успешно
2025-05-16 22:31:38 - get_link - INFO - Капча решена успешно
2025-05-16 22:31:38 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:31:38 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:31:38 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:31:38 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:31:38 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:31:38 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:31:38 - get_link - INFO - Капча решена успешно
2025-05-16 22:31:38 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:31:38 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:31:38 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:31:38 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:31:38 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:31:38 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:31:39 - get_link - INFO - Попытка решения капчи #2
2025-05-16 22:31:39 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:31:39 - get_link - INFO - Попытка решения капчи #2
2025-05-16 22:31:39 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:31:40 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:31:40 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:31:47 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 22:31:49 - get_link - INFO - Капча решена успешно
2025-05-16 22:31:49 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:31:49 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:31:50 - get_link - INFO - Попытка решения капчи #3
2025-05-16 22:31:50 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:31:53 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[2]/div/a
2025-05-16 22:31:53 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:31:58 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 22:32:01 - get_link - INFO - Попытка решения капчи #4
2025-05-16 22:32:01 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:32:09 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 22:32:12 - get_link - INFO - Попытка решения капчи #5
2025-05-16 22:32:12 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:32:21 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 22:32:24 - get_link - WARNING - Достигнуто максимальное количество попыток решения капчи
2025-05-16 22:32:24 - get_link - INFO - Всего найдено ссылок: 0
2025-05-16 22:32:24 - get_link - WARNING - Не найдены подходящие ссылки для запроса site:yandex.ru яндекс игры (попытка 1)
2025-05-16 22:32:29 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 2)
2025-05-16 22:32:31 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:32:31 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:32:44 - get_link - INFO - Найдена ссылка #1 по XPath: //*[@id="search-result"]/li[2]/div/div[1]/a
2025-05-16 22:32:44 - get_link - INFO - Всего найдено ссылок: 1
2025-05-16 22:35:12 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:35:12 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:35:12 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:35:12 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:35:12 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:35:12 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:35:12 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:35:12 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 22:35:14 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:35:14 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:35:14 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:35:14 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:35:14 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:35:14 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:35:14 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:35:14 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:35:14 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:35:14 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:35:14 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:35:14 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:35:14 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:35:14 - get_link - INFO - Попытка решения капчи #1
2025-05-16 22:35:14 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:35:14 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:35:22 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 22:35:22 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 22:35:24 - get_link - INFO - Капча решена успешно
2025-05-16 22:35:24 - get_link - INFO - Капча решена успешно
2025-05-16 22:35:25 - get_link - INFO - Попытка решения капчи #2
2025-05-16 22:35:25 - get_link - INFO - Попытка решения капчи #2
2025-05-16 22:35:25 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:35:25 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:35:33 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 22:35:33 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 22:35:36 - get_link - INFO - Попытка решения капчи #3
2025-05-16 22:35:36 - get_link - INFO - Попытка решения капчи #3
2025-05-16 22:35:36 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:35:36 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:35:44 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 22:35:44 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 22:35:47 - get_link - INFO - Попытка решения капчи #4
2025-05-16 22:35:47 - get_link - INFO - Попытка решения капчи #4
2025-05-16 22:35:47 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:35:47 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 22:35:50 - get_link - ERROR - Не удалось решить капчу с изображениями: 404 Client Error: Not found for url: https://ext.captcha.yandex.net/image?key=00AfGWqOb5RCMUJDOVNvkylSd0423a72&data=img
2025-05-16 22:35:50 - get_link - ERROR - Не удалось решить капчу с изображениями: 404 Client Error: Not found for url: https://ext.captcha.yandex.net/image?key=00AfGWqOb5RCMUJDOVNvkylSd0423a72&data=img
2025-05-16 22:35:53 - get_link - ERROR - Ошибка при проверке наличия формы капчи: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=136.0.7103.114)
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x007705D3]
	(No symbol) [0x0075FE20]
	(No symbol) [0x0077DD1F]
	(No symbol) [0x007E3E8C]
	(No symbol) [0x007FDF19]
	(No symbol) [0x007DD096]
	(No symbol) [0x007AC840]
	(No symbol) [0x007AD6A4]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	GetHandleVerifier [0x009574D8+92440]
	GetHandleVerifier [0x00957680+92864]
	GetHandleVerifier [0x00942070+5296]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 145, in _is_captcha_form_present
    return bool(self.driver.find_elements(By.XPATH, '/html/body/div[1]/div/main/div/form'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 936, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=136.0.7103.114)
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x007705D3]
	(No symbol) [0x0075FE20]
	(No symbol) [0x0077DD1F]
	(No symbol) [0x007E3E8C]
	(No symbol) [0x007FDF19]
	(No symbol) [0x007DD096]
	(No symbol) [0x007AC840]
	(No symbol) [0x007AD6A4]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	GetHandleVerifier [0x009574D8+92440]
	GetHandleVerifier [0x00957680+92864]
	GetHandleVerifier [0x00942070+5296]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]

2025-05-16 22:35:53 - get_link - ERROR - Ошибка при проверке наличия формы капчи: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=136.0.7103.114)
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x007705D3]
	(No symbol) [0x0075FE20]
	(No symbol) [0x0077DD1F]
	(No symbol) [0x007E3E8C]
	(No symbol) [0x007FDF19]
	(No symbol) [0x007DD096]
	(No symbol) [0x007AC840]
	(No symbol) [0x007AD6A4]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	GetHandleVerifier [0x009574D8+92440]
	GetHandleVerifier [0x00957680+92864]
	GetHandleVerifier [0x00942070+5296]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 145, in _is_captcha_form_present
    return bool(self.driver.find_elements(By.XPATH, '/html/body/div[1]/div/main/div/form'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 936, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=136.0.7103.114)
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x007705D3]
	(No symbol) [0x0075FE20]
	(No symbol) [0x0077DD1F]
	(No symbol) [0x007E3E8C]
	(No symbol) [0x007FDF19]
	(No symbol) [0x007DD096]
	(No symbol) [0x007AC840]
	(No symbol) [0x007AD6A4]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	GetHandleVerifier [0x009574D8+92440]
	GetHandleVerifier [0x00957680+92864]
	GetHandleVerifier [0x00942070+5296]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]

2025-05-16 22:35:54 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x0077044E]
	(No symbol) [0x007ABB08]
	(No symbol) [0x007DD156]
	(No symbol) [0x007D8C22]
	(No symbol) [0x007D81B6]
	(No symbol) [0x007436C5]
	(No symbol) [0x00743C1E]
	(No symbol) [0x007440AD]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	(No symbol) [0x00743390]
	(No symbol) [0x00742B9D]
	GetHandleVerifier [0x00CC87FC+3701820]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 252, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 137, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 110, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 898, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x0077044E]
	(No symbol) [0x007ABB08]
	(No symbol) [0x007DD156]
	(No symbol) [0x007D8C22]
	(No symbol) [0x007D81B6]
	(No symbol) [0x007436C5]
	(No symbol) [0x00743C1E]
	(No symbol) [0x007440AD]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	(No symbol) [0x00743390]
	(No symbol) [0x00742B9D]
	GetHandleVerifier [0x00CC87FC+3701820]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]

2025-05-16 22:35:54 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x0077044E]
	(No symbol) [0x007ABB08]
	(No symbol) [0x007DD156]
	(No symbol) [0x007D8C22]
	(No symbol) [0x007D81B6]
	(No symbol) [0x007436C5]
	(No symbol) [0x00743C1E]
	(No symbol) [0x007440AD]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	(No symbol) [0x00743390]
	(No symbol) [0x00742B9D]
	GetHandleVerifier [0x00CC87FC+3701820]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 252, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 137, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 110, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 898, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x0077044E]
	(No symbol) [0x007ABB08]
	(No symbol) [0x007DD156]
	(No symbol) [0x007D8C22]
	(No symbol) [0x007D81B6]
	(No symbol) [0x007436C5]
	(No symbol) [0x00743C1E]
	(No symbol) [0x007440AD]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	(No symbol) [0x00743390]
	(No symbol) [0x00742B9D]
	GetHandleVerifier [0x00CC87FC+3701820]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]

2025-05-16 22:35:54 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x0077044E]
	(No symbol) [0x007ABB08]
	(No symbol) [0x007DD156]
	(No symbol) [0x007D8C22]
	(No symbol) [0x007D81B6]
	(No symbol) [0x007436C5]
	(No symbol) [0x00743C1E]
	(No symbol) [0x007440AD]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	(No symbol) [0x00743390]
	(No symbol) [0x00742B9D]
	GetHandleVerifier [0x00CC87FC+3701820]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 252, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 137, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 110, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 898, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x0077044E]
	(No symbol) [0x007ABB08]
	(No symbol) [0x007DD156]
	(No symbol) [0x007D8C22]
	(No symbol) [0x007D81B6]
	(No symbol) [0x007436C5]
	(No symbol) [0x00743C1E]
	(No symbol) [0x007440AD]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	(No symbol) [0x00743390]
	(No symbol) [0x00742B9D]
	GetHandleVerifier [0x00CC87FC+3701820]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]

2025-05-16 22:35:54 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x0077044E]
	(No symbol) [0x007ABB08]
	(No symbol) [0x007DD156]
	(No symbol) [0x007D8C22]
	(No symbol) [0x007D81B6]
	(No symbol) [0x007436C5]
	(No symbol) [0x00743C1E]
	(No symbol) [0x007440AD]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	(No symbol) [0x00743390]
	(No symbol) [0x00742B9D]
	GetHandleVerifier [0x00CC87FC+3701820]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 252, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 137, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 110, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 898, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x0077044E]
	(No symbol) [0x007ABB08]
	(No symbol) [0x007DD156]
	(No symbol) [0x007D8C22]
	(No symbol) [0x007D81B6]
	(No symbol) [0x007436C5]
	(No symbol) [0x00743C1E]
	(No symbol) [0x007440AD]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	(No symbol) [0x00743390]
	(No symbol) [0x00742B9D]
	GetHandleVerifier [0x00CC87FC+3701820]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]

2025-05-16 22:35:54 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:translate.yandex.ru переводчик (попытка 1)
2025-05-16 22:35:54 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:translate.yandex.ru переводчик (попытка 1)
2025-05-16 22:35:59 - get_link - ERROR - Ошибка при поиске (попытка 2): Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x0077044E]
	(No symbol) [0x007ABB08]
	(No symbol) [0x007DD156]
	(No symbol) [0x007D8C22]
	(No symbol) [0x007D81B6]
	(No symbol) [0x007436C5]
	(No symbol) [0x00743C1E]
	(No symbol) [0x007440AD]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	(No symbol) [0x00743390]
	(No symbol) [0x00742B9D]
	GetHandleVerifier [0x00CC87FC+3701820]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 826, in set_page_load_timeout
    self.execute(Command.SET_TIMEOUTS, {"pageLoad": int(float(time_to_wait) * 1000)})
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x0077044E]
	(No symbol) [0x007ABB08]
	(No symbol) [0x007DD156]
	(No symbol) [0x007D8C22]
	(No symbol) [0x007D81B6]
	(No symbol) [0x007436C5]
	(No symbol) [0x00743C1E]
	(No symbol) [0x007440AD]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	(No symbol) [0x00743390]
	(No symbol) [0x00742B9D]
	GetHandleVerifier [0x00CC87FC+3701820]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 34, in get_first_yandex_link
    self.driver.set_page_load_timeout(60)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 828, in set_page_load_timeout
    self.execute(Command.SET_TIMEOUTS, {"ms": float(time_to_wait) * 1000, "type": "page load"})
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x0077044E]
	(No symbol) [0x007ABB08]
	(No symbol) [0x007DD156]
	(No symbol) [0x007D8C22]
	(No symbol) [0x007D81B6]
	(No symbol) [0x007436C5]
	(No symbol) [0x00743C1E]
	(No symbol) [0x007440AD]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	(No symbol) [0x00743390]
	(No symbol) [0x00742B9D]
	GetHandleVerifier [0x00CC87FC+3701820]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]

2025-05-16 22:35:59 - get_link - ERROR - Ошибка при поиске (попытка 2): Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x0077044E]
	(No symbol) [0x007ABB08]
	(No symbol) [0x007DD156]
	(No symbol) [0x007D8C22]
	(No symbol) [0x007D81B6]
	(No symbol) [0x007436C5]
	(No symbol) [0x00743C1E]
	(No symbol) [0x007440AD]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	(No symbol) [0x00743390]
	(No symbol) [0x00742B9D]
	GetHandleVerifier [0x00CC87FC+3701820]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 826, in set_page_load_timeout
    self.execute(Command.SET_TIMEOUTS, {"pageLoad": int(float(time_to_wait) * 1000)})
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x0077044E]
	(No symbol) [0x007ABB08]
	(No symbol) [0x007DD156]
	(No symbol) [0x007D8C22]
	(No symbol) [0x007D81B6]
	(No symbol) [0x007436C5]
	(No symbol) [0x00743C1E]
	(No symbol) [0x007440AD]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	(No symbol) [0x00743390]
	(No symbol) [0x00742B9D]
	GetHandleVerifier [0x00CC87FC+3701820]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 34, in get_first_yandex_link
    self.driver.set_page_load_timeout(60)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 828, in set_page_load_timeout
    self.execute(Command.SET_TIMEOUTS, {"ms": float(time_to_wait) * 1000, "type": "page load"})
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x0094FC83+61635]
	GetHandleVerifier [0x0094FCC4+61700]
	(No symbol) [0x0077044E]
	(No symbol) [0x007ABB08]
	(No symbol) [0x007DD156]
	(No symbol) [0x007D8C22]
	(No symbol) [0x007D81B6]
	(No symbol) [0x007436C5]
	(No symbol) [0x00743C1E]
	(No symbol) [0x007440AD]
	GetHandleVerifier [0x00BD45A3+2701795]
	GetHandleVerifier [0x00BCFD26+2683238]
	GetHandleVerifier [0x00BEAA6E+2793134]
	GetHandleVerifier [0x00966945+155013]
	GetHandleVerifier [0x0096D02D+181357]
	(No symbol) [0x00743390]
	(No symbol) [0x00742B9D]
	GetHandleVerifier [0x00CC87FC+3701820]
	BaseThreadInitThunk [0x76A95D49+25]
	RtlInitializeExceptionChain [0x77D9CEAB+107]
	RtlGetAppContainerNamedObjectPath [0x77D9CE31+561]

2025-05-16 23:36:37 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:36:37 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:36:39 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:36:39 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:36:39 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:36:39 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:36:39 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:36:39 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:36:39 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:36:39 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:36:40 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:36:40 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:36:40 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:36:40 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:36:40 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:36:40 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:36:40 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:36:40 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:36:40 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:36:41 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:36:41 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:36:44 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:36:44 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:36:44 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:36:44 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:36:45 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:36:45 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:36:45 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:36:45 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:36:45 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:36:45 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:36:45 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:36:45 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:36:46 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:36:46 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:36:55 - get_link - INFO - Капча решена успешно
2025-05-16 23:36:55 - get_link - INFO - Капча решена успешно
2025-05-16 23:36:55 - get_link - INFO - Капча решена успешно
2025-05-16 23:36:55 - get_link - INFO - Капча решена успешно
2025-05-16 23:36:56 - get_link - INFO - Капча решена успешно
2025-05-16 23:36:56 - get_link - INFO - Капча решена успешно
2025-05-16 23:36:56 - get_link - INFO - Капча решена успешно
2025-05-16 23:37:05 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 253, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:37:05 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 253, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:37:15 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 253, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:37:15 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:yandex.ru первый президент россии (попытка 1)
2025-05-16 23:37:15 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 253, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:37:15 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:market.yandex.ru катушка зажигания (попытка 1)
2025-05-16 23:37:30 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 253, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:37:30 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 253, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:37:40 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 253, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:37:40 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:yandex.ru первый президент россии (попытка 2)
2025-05-16 23:37:40 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 253, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:37:40 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:market.yandex.ru катушка зажигания (попытка 2)
2025-05-16 23:37:55 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 253, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:37:55 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 253, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:38:05 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 253, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:38:05 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:yandex.ru первый президент россии (попытка 3)
2025-05-16 23:38:05 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 253, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:38:05 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:market.yandex.ru катушка зажигания (попытка 3)
2025-05-16 23:38:58 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:38:58 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:38:58 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:38:58 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:38:58 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:38:58 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:38:58 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:38:59 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:38:59 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:38:59 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:38:59 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:38:59 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:38:59 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:00 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:00 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:00 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:00 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:00 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:00 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:00 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:00 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:00 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:00 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:01 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:01 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:01 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:02 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:02 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:02 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:02 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:02 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:03 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:04 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:04 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:04 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:04 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:04 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:04 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:05 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:05 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:05 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:05 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:05 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:05 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:05 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:05 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:05 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:05 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:05 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:05 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:06 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:06 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:07 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:07 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:07 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:07 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:09 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:09 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:09 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:09 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:14 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:15 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:15 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:17 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:17 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:17 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:17 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:17 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:17 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:19 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:19 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:19 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:20 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:22 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:22 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:23 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:23 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:24 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:25 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:25 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:25 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:25 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:25 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:25 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:25 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:25 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:26 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:26 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:26 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:26 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:27 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:27 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:39:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:27 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:27 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:27 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:27 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:39:27 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:27 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:28 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:29 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:29 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:39:30 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:30 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:30 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:30 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:30 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:30 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:30 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:30 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:31 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:31 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:31 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:31 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:32 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:32 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:32 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:32 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:32 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:32 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:33 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:39:35 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:35 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:36 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:36 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:37 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:39:37 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:39 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:39 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:39 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:39 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:40 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:39:40 - get_link - INFO - Попытка решения капчи #3
2025-05-16 23:39:40 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:41 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:41 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:41 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:41 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:41 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:42 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:42 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:42 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:43 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:43 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:39:43 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:yandex.ru знак зодиака рак (попытка 1)
2025-05-16 23:39:44 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:44 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:44 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:44 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:44 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:44 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:44 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:44 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:44 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:44 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:44 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:44 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:45 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:45 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:45 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:45 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:45 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:46 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:46 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:46 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:46 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:46 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:46 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:39:46 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:48 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:48 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:48 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:48 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:39:49 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:49 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:49 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:49 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:49 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:49 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:49 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:49 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:49 - get_link - INFO - Попытка решения капчи #4
2025-05-16 23:39:49 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:50 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:50 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:50 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:50 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:51 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:51 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:53 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:53 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:53 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:39:53 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:39:55 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:57 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:39:58 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:39:58 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:58 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:58 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:39:58 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:58 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:59 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:59 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:59 - get_link - INFO - Капча решена успешно
2025-05-16 23:39:59 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:39:59 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:00 - get_link - INFO - Попытка решения капчи #5
2025-05-16 23:40:00 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:00 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:01 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:02 - get_link - INFO - Капча решена успешно
2025-05-16 23:40:02 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:03 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:03 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:03 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:03 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:03 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:03 - get_link - INFO - Попытка решения капчи #3
2025-05-16 23:40:03 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:03 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:04 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:04 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:04 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:04 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:04 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:04 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:05 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:05 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:05 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:05 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:05 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:05 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:08 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:08 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:08 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:08 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:08 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:yandex.ru знак зодиака рак (попытка 2)
2025-05-16 23:40:08 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:09 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:09 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:09 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:09 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:10 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:10 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:10 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:10 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:10 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:10 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:10 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:10 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:11 - get_link - WARNING - Достигнуто максимальное количество попыток решения капчи
2025-05-16 23:40:11 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:11 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:12 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:12 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:14 - get_link - INFO - Попытка решения капчи #3
2025-05-16 23:40:14 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:14 - get_link - INFO - Попытка решения капчи #4
2025-05-16 23:40:14 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:15 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:15 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:16 - get_link - INFO - Капча решена успешно
2025-05-16 23:40:16 - get_link - INFO - Капча решена успешно
2025-05-16 23:40:16 - get_link - INFO - Капча решена успешно
2025-05-16 23:40:17 - get_link - INFO - Капча решена успешно
2025-05-16 23:40:17 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:17 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:18 - get_link - INFO - Попытка решения капчи #3
2025-05-16 23:40:18 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:18 - get_link - INFO - Попытка решения капчи #3
2025-05-16 23:40:18 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:19 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:19 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:20 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:20 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:yandex.ru фильмы про акул (попытка 1)
2025-05-16 23:40:21 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:21 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:21 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:21 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:21 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:21 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:22 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:22 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:23 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:23 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:24 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:25 - get_link - INFO - Попытка решения капчи #5
2025-05-16 23:40:25 - get_link - INFO - Попытка решения капчи #4
2025-05-16 23:40:25 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:25 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:25 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:25 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:26 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:26 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:26 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:26 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:27 - get_link - INFO - Капча решена успешно
2025-05-16 23:40:28 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:28 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:28 - get_link - INFO - Попытка решения капчи #4
2025-05-16 23:40:28 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:28 - get_link - INFO - Попытка решения капчи #4
2025-05-16 23:40:28 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:29 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:29 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:31 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:31 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:music.yandex.ru пицца оружие (попытка 1)
2025-05-16 23:40:31 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:31 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:33 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:33 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:33 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:34 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:34 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:yandex.ru знак зодиака рак (попытка 3)
2025-05-16 23:40:35 - get_link - INFO - Капча решена успешно
2025-05-16 23:40:35 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:36 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:36 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:36 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 2)
2025-05-16 23:40:36 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:36 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:36 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:36 - get_link - INFO - Попытка решения капчи #3
2025-05-16 23:40:36 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:36 - get_link - WARNING - Достигнуто максимальное количество попыток решения капчи
2025-05-16 23:40:36 - get_link - INFO - Попытка решения капчи #5
2025-05-16 23:40:36 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:37 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:37 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:38 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:38 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:39 - get_link - INFO - Попытка решения капчи #5
2025-05-16 23:40:39 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:39 - get_link - INFO - Попытка решения капчи #5
2025-05-16 23:40:39 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:39 - get_link - INFO - Попытка решения капчи #3
2025-05-16 23:40:39 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:39 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:42 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:42 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:43 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:43 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:43 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:43 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:43 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:44 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:46 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:46 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:yandex.ru фильмы про акул (попытка 2)
2025-05-16 23:40:46 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:46 - get_link - INFO - Попытка решения капчи #3
2025-05-16 23:40:46 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:46 - get_link - WARNING - Достигнуто максимальное количество попыток решения капчи
2025-05-16 23:40:46 - get_link - INFO - Попытка решения капчи #4
2025-05-16 23:40:46 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:47 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:47 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:50 - get_link - WARNING - Достигнуто максимальное количество попыток решения капчи
2025-05-16 23:40:50 - get_link - WARNING - Достигнуто максимальное количество попыток решения капчи
2025-05-16 23:40:50 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:50 - get_link - INFO - Попытка решения капчи #4
2025-05-16 23:40:50 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:51 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:52 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:52 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:52 - get_link - INFO - Капча решена успешно
2025-05-16 23:40:53 - get_link - INFO - Капча решена успешно
2025-05-16 23:40:54 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:54 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:54 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:yandex.ru знак зодиака рак (попытка 1)
2025-05-16 23:40:54 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:54 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:40:55 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:40:55 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:55 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:56 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:40:56 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:40:56 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:56 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:translate.yandex.ru как переводится на русский (попытка 1)
2025-05-16 23:40:57 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:40:57 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:40:57 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:57 - get_link - INFO - Попытка решения капчи #4
2025-05-16 23:40:57 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:57 - get_link - INFO - Попытка решения капчи #5
2025-05-16 23:40:57 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:40:59 - get_link - INFO - Капча решена успешно
2025-05-16 23:41:00 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:41:00 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:41:00 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:41:00 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:41:01 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:41:01 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:41:01 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:41:01 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:41:03 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:41:03 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:41:03 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:41:05 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:41:05 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:41:05 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:41:05 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:41:06 - get_link - INFO - Капча решена успешно
2025-05-16 23:41:07 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:41:07 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:www.kinopoisk.ru годзилла 2 король монстров фильм 2019 (попытка 1)
2025-05-16 23:41:08 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:41:08 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:41:08 - get_link - WARNING - Достигнуто максимальное количество попыток решения капчи
2025-05-16 23:41:08 - get_link - INFO - Попытка решения капчи #5
2025-05-16 23:41:08 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:41:09 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:41:10 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:41:10 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:41:10 - get_link - INFO - Капча решена успешно
2025-05-16 23:41:10 - get_link - INFO - Капча решена успешно
2025-05-16 23:41:10 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:41:10 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:music.yandex.ru человек яйца (попытка 1)
2025-05-16 23:41:10 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:41:10 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:tv.yandex.ru программа передач на сегодня великий новгород (попытка 1)
2025-05-16 23:41:11 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:41:11 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:yandex.ru фильмы про акул (попытка 3)
2025-05-16 23:41:12 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 2)
2025-05-16 23:41:12 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:41:13 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:41:13 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:41:13 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:41:13 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:41:14 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:41:15 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:41:15 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:41:15 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 2)
2025-05-16 23:41:16 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 2)
2025-05-16 23:41:16 - get_link - INFO - Капча решена успешно
2025-05-16 23:41:16 - get_link - ERROR - Не удалось решить капчу с изображениями: Не удалось получить результат
2025-05-16 23:41:17 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:41:17 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:41:17 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:41:17 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:41:17 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:41:17 - get_link - INFO - Обнаружена капча, пытаемся решить (попытка 1)
2025-05-16 23:41:18 - get_link - ERROR - Не удалось получить ссылку на позиции 2: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:41:18 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:41:18 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:41:19 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:41:19 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:41:19 - get_link - INFO - Попытка решения капчи #1
2025-05-16 23:41:19 - get_link - WARNING - Неизвестный тип капчи (попытка 1)
2025-05-16 23:41:19 - get_link - ERROR - Не удалось получить ссылку на позиции 3: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 251, in _find_matching_link
    element = self.wait.until(EC.presence_of_element_located((By.XPATH, xpath)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

2025-05-16 23:41:19 - get_link - WARNING - Не найдена подходящая ссылка для запроса site:yandex.ru знак зодиака рак (попытка 2)
2025-05-16 23:41:19 - get_link - WARNING - Достигнуто максимальное количество попыток решения капчи
2025-05-16 23:41:20 - get_link - INFO - Попытка решения капчи #2
2025-05-16 23:41:20 - get_link - INFO - Капча решена успешно
2025-05-16 23:41:20 - get_link - INFO - Обнаружена капча с изображениями
2025-05-16 23:41:20 - get_link - ERROR - Ошибка при поиске (попытка 1): ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1395, in getresponse
    response.begin()
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 34, in get_first_yandex_link
    self._perform_search(query)
  File "C:\Users\priva\Desktop\Zapros2\get_link.py", line 69, in _perform_search
    self.driver.get(f"https://yandex.ru/search/?text={encoded_query}&lr=213")
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 454, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1395, in getresponse
    response.begin()
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priva\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
